version: '3.9'
services:
  target:
    container_name: target
    build:
      context: ./scenario/target/.
      dockerfile: Dockerfile
    networks:
      malcolm_net:
        ipv4_address: 192.170.1.5
  source:
    container_name: source
    build:
      context: ./scenario/source/.
      dockerfile: Dockerfile
    networks:
      malcolm_net:
        ipv4_address: 192.170.1.3
  spoofer:
    container_name: spoofer
    build:
      context: ./scenario/spoofer/.
      dockerfile: Dockerfile
    volumes:
      - .:/ft_malcolm
    networks:
      malcolm_net:
        ipv4_address: 192.170.1.4



networks:
  malcolm_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.170.1.0/24
